services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
